version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=./target/*.jar
    ports:
      - 80:80
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/persons_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - spring-mysql-network
  mysqldb:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=persons_db
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-network
volumes:
  mysql-data:
networks:
  spring-mysql-network:
    name: spring-mysql-network