version: '3.8'
services:
  mysql_db:
    container_name: mysql_container
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    #networks:
      #- api-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - mysql_db
    ports:
      - 9090:8080
    #networks:
      #- api-network

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=./target/*.jar
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_NAME=${DB_NAME}
        - DB_SERVER=mysql_db
    container_name: myapp
    #environment:
      #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/persons_db
      #- SPRING_DATASOURCE_USERNAME=admin
      #- SPRING_DATASOURCE_PASSWORD=123456
      #- DB_PASSWORD=${DB_PASSWORD}
      #- DB_USER=${DB_USER}
      #- DB_NAME=${DB_NAME}
      #- DB_SERVER=mysql_db
    depends_on:
      - mysql_db
    ports:
      - 80:80
    #networks:
      #- api-network
#networks:
  #api-network:
volumes:
  mysql-data: